version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_USER: gps
      POSTGRES_PASSWORD: gps12345
      POSTGRES_DB: gps
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gps-net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - gps-net

volumes:
  postgres_data:

networks:
  gps-net:
